### ISSUE TITLE
Uncaught AxiosError AxiosError

### ISSUE THREAD

**Issue by entitymob** [maelgangloff/kdecole-api#298]
bonjour,
j'ai reçu une erreur du module Axios quand j'essaye de m'authentifier.

Voici mon code (simple) :
```javascript
const { Kdecole, ApiVersion, ApiUrl } = require('kdecole-api')

const user = new Kdecole("AUTH", ApiVersion.PROD_WEBCOLLEGE_SEINESAINTDENIS, 0, ApiUrl.PROD_WEBCOLLEGE_SEINESAINTDENIS)
user.starting()
```

voici mon erreur :
```
Uncaught AxiosError AxiosError
    at processPromiseRejections (internal/process/promises:246:11)
    at processTicksAndRejections (internal/process/task_queues:97:32)
```

**Comment by maelgangloff** [comment]
Bonjour,
Merci d'avoir ouvert une issue !

Êtes vous sûr que votre token est valide ? Essayez d'en regénérer un puis de réessayer votre code:
```js
const { Kdecole, ApiUrl, ApiVersion } = require('kdecole-api')

Kdecole.login(username, uniquePassword, ApiVersion.PROD_WEBCOLLEGE_SEINESAINTDENIS, ApiUrl.PROD_WEBCOLLEGE_SEINESAINTDENIS).then(token => console.log(token)) // Affiche son token dans la console
```

L'erreur Axios que vous mentionnez n'est pas très explicite... essayez ce code pour obtenir une erreur plus précise:
```js
const { Kdecole, ApiVersion, ApiUrl } = require('kdecole-api')

const user = new Kdecole("AUTH", ApiVersion.PROD_WEBCOLLEGE_SEINESAINTDENIS, 0, ApiUrl.PROD_WEBCOLLEGE_SEINESAINTDENIS)
user.starting().catch(console.log)
```
Si l'API renvoie un code HTTP 403 (Forbidden), c'est que le token fourni est invalide et qu'il faut le regénérer (cf [README.md](https://github.com/maelgangloff/kdecole-api/blob/master/README.md)

**Comment by entitymob** [comment]
j'ai essayé et ça marche, merci beaucoup et bonne soirée
